### ISSUE TITLE
Possibility to import custom content from local directory

### ISSUE THREAD

**Issue by tintinhamans** [bgior/weavelore#4]
Would be nice if it was possible to automatically import custom content from a local directory on the server instead of relying on the user to import it themselves.

**Comment by bgior** [comment]
Do you mean that you would like to deploy a different version of the project that, instead of loading the SRD file by default, loads all the content files in a certain directory within the project?

**Comment by tintinhamans** [comment]
Yes, that would be correct. This way, if people chose to host it themselves, they can pre-load any custom content that they want for their users. 

In my case, our DM would like to add his homebrew spells for the whole party to access. While this is already possible to do by exporting the content, it requires every party member to import it on their PC and checking everyone is on the same version.

At the moment only `/srd.json` is being loaded when the content is empty. A possible implementation of this idea could be to load `/srd.json` as well as the content in `/preload/*.json`.

**Comment by tintinhamans** [comment]
Another option would be to write all changes to the server instead of the user's browser. But that would mean either trusting the users not to make changes or implementing some sort of authentication on the content import page.

Yet another option would be to have a config file that sets the list of content URLs to be loaded.

**Comment by bgior** [comment]
I think the config file approach is the easiest to implement. I've added a `.env` file to the root of the project. There we can define any list of URLs (relative or absolute) to be loaded by default, like:
`VUE_APP_DEFAULT_CONTENTFILES=/file1.json,/file2.json,https://foo.bar/file3.json`

You can create a `.env.local` file to have a git-ignored [override](https://cli.vuejs.org/guide/mode-and-env.html#environment-variables) of the default `.env` file.

Sounds good? It's available on the develop branch.

**Comment by tintinhamans** [comment]
That sounds perfect, thanks a lot!
