### ISSUE TITLE
Missing Chromatic Orb Spell

### ISSUE THREAD

**Issue by stealthhacker** [bgior/weavelore#5]
I noticed your missing Chromatic Orb in your spell list and cards.

http://dnd5e.wikidot.com/spell:chromatic-orb

**Comment by bgior** [comment]
Hey, thanks for reporting. Unfortunately that spell is [not on the SRD](https://github.com/bgior/weavelore/wiki/Content-FAQ).

Feel free to contact me if you would like to know more about using other sources.
